### ISSUE TITLE
[TRANSLATION] Untranslated dialog option with the twins

### ISSUE THREAD

**Issue by JakobCh** [ArctynFox/WindandMemoryFanTranslation#1]
**Describe the issue**
An option when talking to Tweedledee and Tweedledum at max covenant level is not translated.

**Area Name**
Twins' room

**To Reproduce**
1. Kill the mental hospital boss
2. Enter a covenant with Tweedledee and Tweedledum
3. Keep giving them souls to max the covenant
4. Talk to them again and enter the covenant menu

**Screenshots**
![image](https://github.com/ArctynFox/WindandMemoryFanTranslation/assets/21036789/5a869f0b-90e1-4e02-8842-543f2696a4c6)

**Comment by ArctynFox** [comment]
I have no idea how I missed that, but I've fixed it in the latest commit.
