### ISSUE TITLE
[BUG] wrong insance allocation error/bug

### ISSUE THREAD

**Issue by Criptimnite** [ArctynFox/WindandMemoryFanTranslation#2]
**Describe the issue**
Every 5 or so minutes after launching the game i get an error saying "wrong instance allocation" and it makes the game COMPLETELY unplayable

**Area Name**
Anywhere Everywhere Anytime

**To Reproduce**
1. Go to 'Blacksouls II:Journey to Wind and Memory'
2. Interact with 'Anything or do something'
3. Make choice '...'
...

**Screenshots**
![1000074956](https://github.com/user-attachments/assets/80443eb6-dcde-4cda-baa2-3476c45b3e3a)

Just after reaching 4th phase of the boss(talking flower) the error with happen(mostly)

If possible, please attach a save file 
[Save04.zip](https://github.com/user-attachments/files/17519854/Save04.zip)

**Comment by Criptimnite** [comment]
Its fixed
Completely! 
With this
[patches.json](https://github.com/user-attachments/files/17520511/patches.json)
![1000074976](https://github.com/user-attachments/assets/642f9fb2-1130-41fb-83a5-37ab9d5c9284)
All thanks to this frabjous fellow here
(He made the whole thing)

**Comment by ArctynFox** [comment]
This is probably a JoiPlay specific issue, I don't plan to fix it since JoiPlay is 3rd party and can have separate unexpected errors. If the same thing occurs on Windows, I'll look into it.
