### ISSUE TITLE
[BUG]/[TRANSLATION] (only keep whichever pertains to your issue)

### ISSUE THREAD

**Issue by antarine** [ArctynFox/WindandMemoryFanTranslation#3]
Essentially, I have an issue where I can't redeem the souls of the bosses I've beaten, in other words I don't have access to the weapons in the game 

In general, the entire area of the issue is practically just the game itself as I practically can't redeem the soul of conceit or the soul of Ghost Train

I am not really sure how to reproduce 

this problem as I am unsure where the source came from 

I don't exactly think I can screenshot this, as it's more of "you understand it once you experience it" type thing but I do have a recording but github has a restraining file size of less then 10 MB 

the zip file should contain the mp4 of the problem and the save file
[save file.zip](https://github.com/user-attachments/files/17823644/save.file.zip)

**Comment by ArctynFox** [comment]
This is not a bug, there just aren't boss weapons pertaining to the mod boss souls. This might be something the dev team adds in when they release the full game, but for this demo, they just don't exist.
